language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - "node_modules"
before_script:
  - npm install -g gulp-cli
script:
  - gulp build
branches:
  except:
    - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: master
  on:
    branch: develop
