language: python
python:
  - "3.5"
install:
  - pip install awscli
script:
  -
deploy:
  on:
    repo: fassko/fassko.github.com
    branch: master
  provider: s3
  access_key_id: AKIAIFQ6DJAUYXMZ7RSA
  secret_access_key: $AWS_SECRET_KEY
  bucket: kristaps.me
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  endpoint: kristaps.me.s3-website-eu-west-1.amazonaws.com
  cache_control: "max-age=21600"
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  email: false